### ISSUE TITLE
[TC_AUTHOR_53]: Text Xblock does not save paragraph break formatting when the table is followed by text

### ISSUE THREAD

**Issue by yuliiazubak** [openedx/wg-build-test-release#370] opened 2024-05-28 16:49 UTC
### Release

Redwood

### Expected behavior

The saved version of the xblock should retain the same formatting Instructor created for the xblock. The text after the table should be displayed with the new paragraph.
![Text xblock editing](https://github.com/openedx/wg-build-test-release/assets/171051201/afa7ef17-6a9a-42b9-85b9-887b75130e53)

### Actual behavior

The saved version does not retain the paragraph break after the table. The text added after the table appears immediately after the table without any paragraph break.
![student view](https://github.com/openedx/wg-build-test-release/assets/171051201/90555c89-c884-47ae-a8c5-47168c80f918)
![Studio xblock view](https://github.com/openedx/wg-build-test-release/assets/171051201/0c47ced4-b5d2-4a04-92be-e9daadfeb110)

### Steps to reproduce

1. In Studio select an option to edit Text xblock.
2. Add a Table to the body of the Xblock.
3. Add a paragraph after the table.
4. Add text.
5. save Xblock

### Additional information

Tried adding multiple paragraph breaks and horizontal lines in between the table and the text, but the result was always the same - upon saving the xblock, the formatting is as in the screenshots.

**Comment by yuliiazubak** [comment] 2024-05-28 16:49
label: release testing

**Comment by mariajgrimaldi** [comment] 2024-05-31 04:34
Thanks for the report! I couldn't replicate this on the redwood sandbox:
![image](https://github.com/openedx/wg-build-test-release/assets/64440265/512017cb-fbd0-4724-9ec4-9cd40adfc417)

Am I missing something in the setup?

**Comment by yuliiazubak** [comment] 2024-05-31 07:09
Not sure what can be wrong with the setup. If it's helpful, please, find the link to the unit in the sendbox - https://studio.redwood.demo.edly.io/container/block-v1:openedx+redwood-testing+demo+type@vertical+block@4773278f08e14643973fa548b952cc61#block-v1:openedx+redwood-testing+demo+type@html+block@fc6cada4b924423d8cdb1f5205fed913 

https://github.com/openedx/wg-build-test-release/assets/171051201/d894d578-95db-4859-8de1-2f829d5dea50

**Comment by mariajgrimaldi** [comment] 2024-06-02 16:09
Thank you! Now I can confirm it's happening. Here's the exported course so we can use it for testing: 
[course.kv5s4klf.tar.gz](https://github.com/user-attachments/files/15525937/course.kv5s4klf.tar.gz)

I'll open an issue in the corresponding repo.

**Comment by mariajgrimaldi** [comment] 2024-06-02 16:29
I tested the same setup in the legacy editor, and it also happens there. I think this might be a misuse of the editor. Could you try other examples of tables and breaklines?

**Comment by yuliiazubak** [comment] 2024-06-04 07:26
I tried other examples of tables and breaklines, but the issues did not occur for me this time

**Comment by mariajgrimaldi** [comment] 2024-06-06 02:50
Thank you for testing those out! I'll close this issue since we cannot reproduce it with other configurations. In any case, it can be reopened if needed.

**Closed by mariajgrimaldi** 2024-06-06 02:50 UTC
Labels: enhancement, release testing, redwood
