### ISSUE TITLE
[TC_AUTHOR_87] > Enable/disable Progress page

### ISSUE THREAD

**Issue by jramnai** [openedx/wg-build-test-release#278] opened 2023-04-29 08:07 UTC
**Steps to reproduce:**

1. Go to the studio and open any course
2. Click on Content > Pages & Resources
3. Click the gear icon on the Progress card shown on this page

**Expected Result:**
It should open the progress modal to enable/disable.

**Actual Result:**
Getting the following error page (https://apps.palm.demo.overhang.io/course-authoring/course/course-v1:TestX+Course+1/pages-and-resources/progress/settings)
![image](https://user-images.githubusercontent.com/29940571/235291950-e5d19bb1-08ae-45ba-8bb4-827ab4ab5925.png)

**Browser console error:**
![image](https://user-images.githubusercontent.com/29940571/235292028-5085c9e5-8256-459a-87fe-665899c105dc.png)

**Comment by jramnai** [comment] 2023-04-29 08:08
label: palm testing

**Comment by ghassanmas** [comment] 2023-04-29 11:25
While investaging I was able to duplicate the problem and fonud that the issue is that course authroing MFE expect `ENABLE_PROGRESS_GRAPH_SETTINGS` this setting to be of a type string [hence](https://github.com/openedx/frontend-app-course-authoring/blob/9a567b875e57f58b2f3b033b21cae92c46a0a388/src/pages-and-resources/progress/Settings.jsx#L13)
`const showProgressGraphSetting = getConfig().ENABLE_PROGRESS_GRAPH_SETTINGS.toLowerCase() === 'true';`

However tutor-mfe returns it as of type of `Boolean` [hence](https://github.com/overhangio/tutor-mfe/blob/b081cf9c7d7a9ecd4045dad4a26a72f00db5e6d7/tutormfe/patches/openedx-lms-production-settings#L56)` "ENABLE_PROGRESS_GRAPH_SETTINGS": True,` . 

So resolve we need either
1. update tutor-mfe to return it as String
2. Create upstream fix so that it parse it as String before calling `toLowerCase` function i.e `Sring(getConfig().ENABLE_PROGRESS_GRAPH_SETTINGS).toLowerCase() === 'true';`

In my opinion the second approach is better, given its expected for a toggle to be of a type `Boolean`

**Comment by mariajgrimaldi** [comment] 2023-05-03 03:16
Thank you so much @ghassanmas for the insight! I opened a [draft PR](https://github.com/openedx/frontend-app-course-authoring/pull/495) with the implementation, I'll be getting it ready for review as soon as I can :)

**Comment by ghassanmas** [comment] 2023-05-03 07:50
Thanks @mariajgrimaldi and I guess it should be added to list PRs that would be backported #261

**Comment by mariajgrimaldi** [comment] 2023-05-10 13:16
Ready for review: https://github.com/openedx/frontend-app-course-authoring/pull/495

**Comment by mariajgrimaldi** [comment] 2023-05-31 17:12
I asked for help in a maintainers slack channel. Let's see how it goes.

**Comment by mariajgrimaldi** [comment] 2023-06-13 14:37
The change worked, now I can hide the progress page. But I haven't been able to hide the progress graph using the configuration shown by the MFE --or I don't get how it works. Either way, I've opened an issue in the MFE repo: https://github.com/openedx/frontend-app-course-authoring/issues/517

I'm closing this now since the root issue was resolved.

**Closed by mariajgrimaldi** 2023-06-13 14:37 UTC
Labels: palm testing
