### ISSUE TITLE
[TC_LEARNER_39] Notes failed to load by default

### ISSUE THREAD

**Issue by cmltaWt0** [openedx/wg-build-test-release#227] opened 2022-11-07 11:32 UTC
Notes failed to load by default.

Steps:
- Enable Notes in a Course Advanced settings
- Open Course as a Student
- Check Notes tab
- Open any Unit in a subsection
- Select text to note
- Save the note
- Check the Note tab
- Return to the Course Subsection
- Check that the prviously noted text is selected and can be seen

Status: FAILED

![image](https://user-images.githubusercontent.com/877401/200299136-1896c2ef-c41c-4dde-99de-6463b93a35c4.png)

Important notes:
- the issue is reproducible but it works fine for the first time
- need to walk through the units
- to fix the issue for a current Unit - just click `Hide Notes` and than `Show notes` again (literally reboot the PC and try it again)

![image](https://user-images.githubusercontent.com/877401/200299700-9b385582-321c-4b39-aa00-ecc79428ba0e.png)
![image](https://user-images.githubusercontent.com/877401/200299746-d86f5dba-59bc-406a-8921-113611ddf4fa.png)
![image](https://user-images.githubusercontent.com/877401/200299779-6982b5f1-589b-4510-9e82-16c261384020.png)
![image](https://user-images.githubusercontent.com/877401/200299811-db511f16-8046-4490-b329-91eccb6d615d.png)

### Links

- [ ] https://github.com/openedx/frontend-app-learning/issues/1005

**Comment by jfavellar90** [comment] 2022-11-17 14:56
According to my investigations, this is a problem related to a discrepancy between the management of the notes in the MFE and the Iframe serving an xblock unit content.

**How it's decided if the student notes must be rendered when a courseware unit page is loaded?**

As I already mentioned, the unit content is loaded through an Iframe, for instance, the content [here](https://apps.olive.demo.overhang.io/learning/course/course-v1:edX+DemoX+Demo_Course/block-v1:edX+DemoX+Demo_Course+type@sequential+block@19a30717eff543078a5d94ae9d6c18a5/block-v1:edX+DemoX+Demo_Course+type@vertical+block@867dddb6f55d410caaa9c1eb9c6743ec) uses the Iframe loaded from [here](https://olive.demo.overhang.io/xblock/block-v1:edX+DemoX+Demo_Course+type@vertical+block@867dddb6f55d410caaa9c1eb9c6743ec?show_title=0&show_bookmark_button=0&recheck_access=1&view=student_view)

There's a decorator in https://github.com/openedx/edx-platform/blob/open-release/olive.master/lms/djangoapps/edxnotes/decorators.py which determines if the **edxnotes visibility** is enabled or not (check the [specific line](https://github.com/openedx/edx-platform/blob/open-release/olive.master/lms/djangoapps/edxnotes/decorators.py#L55)) and based on that value, notes are rendered on the page or not. This visibility value depends on a student preference stored in the table **courseware_xmodulestudentinfofield**. The preference name is "**edxnotes_visibility**". If the preference is not present for the currently logged-in user, the notes visibility is enabled by default.

**How the frontend-app-learning MFE determines if the notes are visible or not?**

The MFE does not determine if the notes should be highlighted the first time a unit page is loaded, however, it stores the notes visibility value, which is taken from a call to the courseware API (https://github.com/openedx/frontend-app-learning/blob/open-release/olive.master/src/courseware/data/api.js#L128). This API returns the values for notes in the format below:

```
notes:
  enabled: true
  visible: true
```

And this API always returns the `visible` field with a `true` value, ignoring the "edxnotes_visibility" preference of the user. This generates an incongruence between the values in the MFE and the Iframe rendering the block unit. For instance, there are cases where the notes are hidden by user preference in the iframe, but the button "Hide Notes" is displayed in the MFE, because, for the MFE, the notes visibility is enabled (value taken from the courseware API).

![Screenshot from 2022-11-17 09-21-05](https://user-images.githubusercontent.com/15217219/202476419-29c1726e-ac71-426f-ab30-6d75a3ca4a3e.png)

**How to resolve the problem**

For me, the solution is to fix the MFE so it gets the notes visibility value properly, taking into account the **edxnotes_visibility** user preference. I'm not sure how to proceed in this case, for now, I'll open an issue directly in the MFE.

**Additional notes**

- This issue is also present in Nutmeg.

**Comment by regisb** [comment] 2022-11-17 16:55
Thank you for this great analysis Jhony.

> And this API always returns the visible field with a true value, ignoring the "edxnotes_visibility" preference of the user.

So if I understand you correctly, the bug comes from the LMS which does not send the right reply to the API call?

**Comment by jfavellar90** [comment] 2022-11-17 17:22
@regisb for me it seems that way. When you call the LMS API (for instance https://olive.demo.overhang.io/api/courseware/course/course-v1:edX+DemoX+Demo_Course) you'll always get notes visibility in `true`, no matter the user notes visibility preference. [This is the view](https://github.com/openedx/edx-platform/blob/open-release/olive.master/openedx/core/djangoapps/courseware_api/views.py#L363) handling such API calls. Additional to this, a small change in the [frontend-app-learning](https://github.com/openedx/frontend-app-learning/blob/open-release/olive.master/src/courseware/course/content-tools/notes-visibility/NotesVisibility.jsx#L28-L32) MFE  is required to change the notes visibility for a user properly.

**Comment by mariajgrimaldi** [comment] 2022-11-21 10:39
label: olive testing

**Comment by jfavellar90** [comment] 2022-11-23 00:28
I decided to publish this issue in the [frontend-app-learning](https://github.com/openedx/frontend-app-learning/issues/1005) repo, I consider the problem resides there, even when the solution could involve a change in edx-platform repo.

**Comment by jalondonot** [comment] 2023-01-23 13:49
@arbrandes, do we have any news from the Frontend WG regarding this issue?

**Comment by jalondonot** [comment] 2023-02-02 15:20
I don't know if this is a high-priority task, @arbrandes. What do you think? should we highlight this issue in the FWG to encourage someone to pick it up and start working on it?

**Comment by jfavellar90** [comment] 2023-02-03 19:56
@jalondonot I don't think at all it's a high-priority issue. This is a legacy issue coming from Nutmeg and last time I checked, it was also present in edx.org (the impact on the platform functionality is low). That said, we can validate if the issue is still happening, and as you suggest, add it to the FWG backlog to be taken and fixed in the next couple of months, preferably before Palma's cutoff. @arbrandes would you agree with this approach?

**Comment by arbrandes** [comment] 2023-02-06 15:49
Totally on board, though I couldn't guarantee this would actually be picked up by Palm.  I could slap a "Palm.1" milestone on it, though, which would automatically make it higher priority.

**Closed** 2023-09-07 15:59 UTC
Labels: bug, release testing
