### ISSUE TITLE
[Test failure] <TC_INSTRUCTOR_18>: <Send bulk email to self, course team and learners not working>

### ISSUE THREAD

**Issue by AntonellaPerrupato** [openedx/wg-build-test-release#409] opened 2024-11-08 14:43 UTC
### Release

Sumac

### Expected behavior

Emails should be sent

### Actual behavior

Tought it seems to be sent, they are not

### Steps to reproduce

https://apps.sumac.demo.edly.io/communications/courses/course-v1:OpenedX+DemoX+DemoCourse/bulk_email
Send email

**Comment by mariajgrimaldi** [comment] 2024-11-18 16:45
@AntonellaPerrupato: This is also probably related to the issue of sending emails. Can you try sending emails to users with protonmail accounts?

**Comment by AntonellaPerrupato** [comment] 2024-11-21 18:08
@mariajgrimaldi  I've created an account, and it still doensn't work

**Comment by mariajgrimaldi** [comment] 2024-11-22 16:52
@AntonellaPerrupato: was, by any chance, this flag missing? https://sumac.demo.edly.io/admin/bulk_email/bulkemailflag/. I tested it after enabling it, and it worked! But if it still doesn't work for you, please provide more details so I can try to reproduce it. Thank you!

**Comment by mariajgrimaldi** [comment] 2024-11-25 09:42
I'm closing this issue since I couldn't reproduce this issue after enabling the bulk email flag. If the issue persists for testers, we can reopen it.

FYI @AntonellaPerrupato

**Closed by mariajgrimaldi** 2024-11-25 09:42 UTC
Labels: release testing, sumac

**Comment by mariajgrimaldi** [comment] 2024-11-29 09:10
@AntonellaPerrupato:  yes, I was. Can you list the steps you've followed?

**Comment by AntonellaPerrupato** [comment] 2024-11-29 13:38
@mariajgrimaldi after enabling the email flag, i sent an email to my proton mail and it worked!!!
