### ISSUE TITLE
[Test failure] <TC_LEARNER_REDWOOD_17>: The learner cannot return to the other sections if he chooses the locked unit in the sidebar

### ISSUE THREAD

**Issue by mariiamoskalenko** [openedx/wg-build-test-release#363] opened 2024-05-23 15:38 UTC
### Release

Redwood

### Expected behavior

As a user, I want to be able to navigate between sections if I'm on the locked unit so that I can easily return to the section with the prerequisite and finish the assignment

### Actual behavior

As a user, I CANNOT navigate between sections if I'm on the locked unit so that I have to return to the outline and spend additional time trying to figure out what is going on

### Steps to reproduce

1. Enrol into the course with subsections with prerequisites ([I created this one for test](https://apps.redwood.demo.edly.io/learning/course/course-v1:RG+RG12+RG12/home)).
2. Start with any subsection.
3. Go to the "locked unit" - with the pre-requisite on the subsection.
4. There are no sections and subsections, just a "course outline".

https://github.com/openedx/wg-build-test-release/assets/91068576/bf0a97f4-d90d-4e29-8d33-198147cb24b9

### Additional information

I'm testing it with the staff user, through Audit mode (maybe it affects smth).

**Comment by mariajgrimaldi** [comment] 2024-05-24 12:11
Thanks for the report! Please, could you test with the student user as well? Here are the credentials: 
username: student@overhang.io
password: student

**Comment by mariiamoskalenko** [comment] 2024-05-24 15:18
For the learner, it's even more strange.
Here is the video - the learner receives an error "There was an error loading this course.".

Here is the video 

https://github.com/openedx/wg-build-test-release/assets/91068576/ef35846a-1b7f-436e-ab24-b462d15a853e

**Comment by mariiamoskalenko** [comment] 2024-05-24 15:19
Should I report it separately for the instructor and for the learner?

**Comment by mariiamoskalenko** [comment] 2024-05-24 15:28
As an Admin now I see that the prerequisite section is locked (but it's not supposed to be locked).

<img width="1135" alt="image" src="https://github.com/openedx/wg-build-test-release/assets/91068576/e34ce27e-892b-4951-84dd-46a54218ce4c">

**Comment by crathbun428** [comment] 2024-05-24 15:53
@mariiamoskalenko and @mariajgrimaldi - I tested this as a student and got the same error message. I went into the course in studio as staff and published and scheduled everything that had not been published or scheduled for the course (most of the locked and prerequisite units).

**Comment by crathbun428** [comment] 2024-05-24 15:58
@mariiamoskalenko and @mariajgrimaldi - I suppose the one question I have is that when staff views a course as "live," shouldn't I see the locked icons on subsections/units locked behind an incomplete pre-requisite? Or is this counter to how things behave today?

**Comment by mariajgrimaldi** [comment] 2024-05-24 21:48
@crathbun428: thanks for figuring this out! 

> I suppose the one question I have is that when staff views a course as "live," shouldn't I see the locked icons on subsections/units locked behind an incomplete pre-requisite? Or is this counter to how things behave today?

We don't have the sidebar in quince, so we can't compare the two. But in quince, we can access the locked content without any sign, as in Redwood:

[Screencast from 24-05-24 17:39:08.webm](https://github.com/openedx/wg-build-test-release/assets/64440265/3a5fd5f5-1958-4add-b144-c05fb26ec0d5)

However, we don't have any indication that that's the locked content. As it's currently happening. 

> (Another weird note about this screenshot is that subsections appear as complete when the units don't appear as complete I can create a minor bug ticket for this, but I suspect this might have to do with how completions are handled, and not have to do with the left-sidebar nav, but I'll document this regardless).

Is this the same behavior as in this [bug report](https://github.com/openedx/frontend-app-learning/issues/1385)?

Thanks!

**Comment by mariiamoskalenko** [comment] 2024-05-28 11:18
@mariajgrimaldi yes, it looks like the same bug.

@mariajgrimaldi should I create a separate bug report for a student? Because I described this one about the Instructor experience.

Also, there is an additional issue: units of the section without the prerequisite are also shown with locked units on the navigation sidebar. Should it be reported as a separate issue?

**Comment by mariajgrimaldi** [comment] 2024-05-28 13:27
@mariiamoskalenko: if all the inconsistent behavior you found is related to the same test case, then we can use the same report. But be sure to include all the info in the issue description. I'll use that info to replicate the behavior and report it to the corresponding repos for maintainers to review. LEARNER_REDWOOD_17 is related to the learner, so we're good.

**Comment by mariajgrimaldi** [comment] 2024-06-02 15:19
@mariiamoskalenko: thank you! In the meantime, I'll open an issue for the weird behavior when the subsections/units are not published so the maintainers know.

**Comment by mariajgrimaldi** [comment] 2024-10-07 11:03
We couldn't reproduce this issue under circumstances other than when the course wasn't completely live/scheduled. An issue was opened to address that specific case so I'll close this as is. Thank you.

**Closed by mariajgrimaldi** 2024-10-07 11:03 UTC
Labels: release testing, redwood
