### ISSUE TITLE
[Test failure] TC_AUTHOR_45: SCORM not working

### ISSUE THREAD

**Issue by angonz** [openedx/wg-build-test-release#430] opened 2024-12-03 20:33 UTC
### Release

Sumac

### Expected behavior

SCORM should work after inserting a SCORM component.

### Actual behavior

Studio shows this error:
**Error: 'openedxscorm.scormxblock' is not a package**
![image](https://github.com/user-attachments/assets/80ec8d94-b477-4b54-a15b-40ea23b21541)

### Steps to reproduce

In Studio, open or create a course.
Add "scorm" to the list of advanced modules.
In a unit, create a SCORM component from the advanced list.

**Comment by AntonellaPerrupato** [comment] 2024-12-04 12:50
@mariajgrimaldi after adding the scorm in advanced settings, I was able to reproduce the error

**Comment by mariajgrimaldi** [comment] 2024-12-05 10:37
@DawoudSheraz: can we confirm that https://github.com/overhangio/openedx-scorm-xblock was properly installed in the image used by the sandbox?

**Comment by DawoudSheraz** [comment] 2024-12-05 10:43
> @DawoudSheraz: can we confirm that https://github.com/overhangio/openedx-scorm-xblock was properly installed in the image used by the sandbox?

It is installed as part of image build, let me try re-building as we have recently pushed scorm v19 and it might not be available on sandbox yet.

**Comment by DawoudSheraz** [comment] 2024-12-05 11:07
I installed scorm-xblock v19 on sandbox but the error is still there https://studio.sumac.demo.edly.io/container/block-v1:Test+tc001+2024+type@vertical+block@5350e8913b5f40f098c4b77571738cfd. I am informing the relevant folks to understand what might be going on here. 
cc: @Danyal-Faheem

**Comment by mariajgrimaldi** [comment] 2024-12-05 11:36
@DawoudSheraz: thank you so much!

**Comment by DawoudSheraz** [comment] 2024-12-05 12:51
@mariajgrimaldi A new version of scorm-xblock has been released, this is fixed now https://studio.sumac.demo.edly.io/container/block-v1:Test+tc001+2024+type@vertical+block@5350e8913b5f40f098c4b77571738cfd#.


![image](https://github.com/user-attachments/assets/42538c59-75e5-4f06-b92e-e46fbb638690)

**Comment by mariajgrimaldi** [comment] 2024-12-05 12:58
@angonz: could you repeat the test case? Thank you!

@DawoudSheraz: thanks a lot for looking into this!

**Comment by AntonellaPerrupato** [comment] 2024-12-05 16:39
@mariajgrimaldi this seems to be working now

**Closed** 2024-12-05 18:21 UTC
Labels: bug, release testing, sumac
