### ISSUE TITLE
[Test failure] TC_AUTHOR_50: The zooming tool image is not working properly

### ISSUE THREAD

**Issue by DeimerM** [openedx/wg-build-test-release#421] opened 2024-11-19 16:07 UTC
### Release

Sumac

### Expected behavior

it expects the image to zoom in on the relevant parts when hovered over.

### Actual behavior

Nothing happens when hovering over the image, and we're getting an error in the developer console. We've even tried downloading the JS file, uploading it to the course, and configuring the new URL, but we're still getting the same error.

### Steps to reproduce

1. Add a component of the type zooming tool image.
2. Try to hover over the image to ensure that it is zooming.
3. Open the developer tools console to discover the error.

### Additional information

![Screenshot From 2024-11-14 11-30-13](https://github.com/user-attachments/assets/0ce13d1a-8f43-499f-b41c-30e3653ae79f)

**Comment by mariajgrimaldi** [comment] 2024-11-22 22:26
Duplicate of https://github.com/openedx/wg-build-test-release/issues/381

**Comment by mariajgrimaldi** [comment] 2024-11-22 22:27
Thank you for the report! This is currently being worked on in the issue I linked above :)

**Comment by mariajgrimaldi** [comment] 2024-11-25 14:55
Here's the PR for the fix: https://github.com/openedx/edx-platform/pull/35661

**Comment by arbrandes** [comment] 2024-12-09 13:11
The PR fixes loading of the script, but the script itself is broken.  The correct solution to supporting this doesn't exist yet, and certainly won't exist in time for Sumac.1, so if this is really a blocker, we should just remove the tool from the `sumac.master` branch until a better way is found.

**Comment by arbrandes** [comment] 2024-12-09 16:10
The DEPR was accepted and the template removed from master.  All that's left is the Sumac backport:

https://github.com/openedx/edx-platform/pull/35998

**Closed** 2024-12-13 14:34 UTC
Labels: release testing, sumac
