### ISSUE TITLE
[Test failure] <TC_LEARNER_5C>: Discovery search doesn't let you clear query after no results found

### ISSUE THREAD

**Issue by lkatsikaris** [openedx/wg-build-test-release#400] opened 2024-10-28 15:33 UTC
### Release

Sumac

### Expected behavior

If the result you are looking for does not exist, it should be able to be cleaned and should not show any results below the  "We couldn't find any results" message. 

### Actual behavior

If the result you are looking for does not exist, it does not allow you to clear it, and continues to show all the courses below the "We couldn't find any results" message.

![image](https://github.com/user-attachments/assets/68447ffa-7400-471a-8d22-eea229044f2f)

### Steps to reproduce

- Log in and go to the Discover section. 
- Search for a nonexistent course/word.

**Comment by mariajgrimaldi** [comment] 2024-11-06 10:58
Thank you for the report! This seems to be the actual behavior of the course catalog page. Here's the implementation that appears to manage this functionality: https://github.com/openedx/edx-platform/blob/open-release/sumac.master/lms/static/js/discovery/models/search_state.js#L85-L116.

So, when the service handling the search (discovery) doesn't return results for the query, like in this case, the list of courses is displayed unfiltered. I also tested this in the Redwood sandbox to confirm this, and it also happens there. 

Since this appears to be the expected behavior, I’ll go ahead and close this issue. Thanks again!

**Comment by mariajgrimaldi** [comment] 2024-11-06 11:00
Sorry, I reopened this because of the "it does not allow to clear it" which is also part of the current behavior, but it could be an enhancement to the implementation so I'll report it somewhere.

**Comment by angonz** [comment] 2024-11-08 21:48
From my perspective, as a regular user, I prefer that a search with an empty result shows an empty list, and a message stating that the search did not return any result, together with a component to reset the search. I think that it is confusing if an empty search returns the full list of courses.
I think it's more a question for the product/UX group. @jmakowski1123 @crathbun428

**Comment by crathbun428** [comment] 2024-12-02 14:39
@angonz - I agree with you, but since what we see here is existing behavior, we'd need to do some work to make this change (showing only a message that there are no results returned for the search term) happen. However, I also think it's ok as long as there is some space between the No results message and the list of courses that are available on the instance. If we were to make a change - I'd like someone from our UI/UX WG to weigh in. 

@mariajgrimaldi - thank you for pointing this out. We can remove this issue since it's an issue with the how the test was written and not a failure introduced with sumac. I'll update the test now to read that you can only clear the search term if it returned results - not possible with no matches.

**Comment by mariajgrimaldi** [comment] 2024-12-02 15:22
@crathbun428: thank you for clarifying! I'm closing this issue now. Thank you all :)

**Closed by mariajgrimaldi** 2024-12-02 15:22 UTC
Labels: release testing, sumac
