### ISSUE TITLE
[Test failure] TC_LEARNER_44: Can't change site to some languages

### ISSUE THREAD

**Issue by Colin-Fredericks** [openedx/wg-build-test-release#347] opened 2024-05-17 14:55 UTC
### Release

Redwood

### Expected behavior

Changing the language for the site should make text appear in other languages.

### Actual behavior

For some languages it works; for others it doesn't.

### Steps to reproduce

1. Open up account settings, like https://apps.redwood.demo.edly.io/account/#site-preferences
2. Click or scroll to "Site Preferences".
3. Click "Edit" next to "Site language".
4. Pick a language. I chose French.
5. Click "Save".
6. Reload the page.
7. Notice that the page is still in English and the setting has swapped back to English. (Not sure what happens if your site-wide default is set to something else.)

In a really weird twist, some languages work and some do not!

* Arabic (العربية) - Works! Including right-to-left. Getting it _back_ out of Arabic was a slight challenge, on account of I do not read Arabic.
* Bahasa Indonesia - No luck. The preference sticks, but the site does not change.
* 中文 (简体) (Simplified Chinese) - Works!
* dansk - Works!
* Espaõl (Latinoamérica) - Works!
* Français - No luck.
* German - Works!
* עברית (Hebrew) - Works!
* साइट प्राथमिकताएँ (Hindi) - Works!
* Italian - Molto bene!
* Kiswahili - Poa kichizi kama ndizi. (That means it works.) (Technically it means "Crazy cool like a banana", and it's basically the only Kiswahili I know.)
* 한국어 (대한민국) (Korean, RoK) - No luck. Site does not change, preference does not stick.
* Português - Works!
* Türkçe - Works!
* Українська (Ukranian) - Works!

So a lot of them work, but not all of them. It seems my initial choice of French was sort of lucky here - I might not have realized this was broken otherwise.

### Additional information

Fun fact: Pasting Hebrew or Arabic into the editor in GitHub gives you some really weird behavior, which I suppose I should have expected.

**Comment by GlugovGrGlib** [comment] 2024-05-29 11:29
@mariajgrimaldi @cmltaWt0 I'm facing exactly the same issue with CORS as @felipemontoya posted above.

I believe the issue is that endpoint `/i18n/setlang/` returns Redirect to `/` instead of JSON response, and when Learner-dashboard MFE is enabled it's being blocked by CORS policy.

Please see screenshots:

Chromium:
<img width="1707" alt="image" src="https://github.com/openedx/wg-build-test-release/assets/22370912/b549a166-5dc5-4c5f-8630-68dc6e88310d">
Firefox:
<img width="958" alt="Screenshot 2024-05-29 at 14 12 03" src="https://github.com/openedx/wg-build-test-release/assets/22370912/eb28706a-ef89-46c4-b4e9-366bbbbe2173">

Did this case pass for Quince, since learner-dashboard MFE was included in the community release?

**Comment by mariajgrimaldi** [comment] 2024-05-30 14:36
@GlugovGrGlib: we don't have a failing report for quince, but I tested in the quince sandbox and got the same cors issue you folks mentioned: https://apps.sandbox.openedx.edly.io/account/

![image](https://github.com/openedx/wg-build-test-release/assets/64440265/91be8a35-996b-4352-9a86-a224334a53f7)

**Comment by mariajgrimaldi** [comment] 2024-05-30 14:57
@GlugovGrGlib: I tested here https://apps.sandbox.openedx.edly.io/account/ and I can confirm is also happening in quince. I can change the language, but I get the CORS error as well. I haven't tested all languages yet.

![image](https://github.com/openedx/wg-build-test-release/assets/64440265/9030f058-408d-44a7-9137-dd4895b7e3dd)

**Comment by mariajgrimaldi** [comment] 2024-08-26 20:07
I'll be opening an issue in the tutor-mfe repo so we can address it there. Thank you all!

**Comment by mariajgrimaldi** [comment] 2024-10-23 11:17
Fixed by https://github.com/openedx/frontend-app-account/pull/1139

**Closed by mariajgrimaldi** 2024-10-23 11:17 UTC
Labels: release testing, redwood
