### ISSUE TITLE
[Test failure] <TC_LEARNER_48>: <Automatic effort estimates are not visible>

### ISSUE THREAD

**Issue by DeanJayMathew** [openedx/wg-build-test-release#351] opened 2024-05-20 04:51 UTC
### Release

Redwood

### Expected behavior

We expect that in the Course Outline there are automatic effort estimates for subsections (e.g. 1 min, 3 min, 5 min, etc).

### Actual behavior

No automatic effort estimates are visible. Here's a link to the course this was tested on: https://apps.redwood.demo.edly.io/learning/course/course-v1:OpenedX+DemoX+2024/home

### Steps to reproduce

Go to a Course Outline (e.g. https://apps.redwood.demo.edly.io/learning/course/course-v1:OpenedX+DemoX+2024/home) and look for automatic effort estimates for subsections (e.g. "1 min", "3 min", "5 min", etc).

```[tasklist]
### Tasks
```

**Comment by DeanJayMathew** [comment] 2024-05-20 04:52
label: release testing

**Comment by DeanJayMathew** [comment] 2024-05-20 04:52
label: redwood

**Comment by mariajgrimaldi** [comment] 2024-05-23 03:17
Thanks for the report, Dean! I tested it in the demo course and can confirm that it is happening. I don't know much about effort estimates, so I'll have to research for a bit before returning to this. Thanks again!

In any case, I'll leave this here as documentation:
https://discuss.openedx.org/t/time-estimates-and-edx-val/9554/6

**Comment by mariajgrimaldi** [comment] 2024-06-03 16:19
I posted my previous comment in the #wg-product-core: https://openedx.slack.com/archives/C057J2D1WU9/p1717431565724849

**Comment by sarina** [comment] 2024-06-03 17:18
Heyo! I remember this feature. I don't believe effort estimates are automatic at all. Going to go scrounge for some docs.

**Comment by sarina** [comment] 2024-06-03 17:24
From https://openedx.org/blog/learning-micro-frontend-now-default-in-maple/, 

> Note that all course videos must have durations in [edx-val](https://github.com/edx/edx-val)Opens a link in a new tab, and courses need to be republished, for the course outline effort estimates (detailed above) to show up.

Reading this, I remember that effort estimates for HTML & Problem Blocks were automatic, and that only videos required extra steps. But, Maple was awhile ago and I could be wrong. Has anyone test if this is a regression from Quince?

**Comment by mariajgrimaldi** [comment] 2024-06-03 17:28
@sarina: it works for problems and text, you can see it [here](https://apps.redwood.demo.edly.io/learning/course/course-v1:Demo+xblocks-v1+2024/home). But not with the demo course for some reason: https://apps.redwood.demo.edly.io/learning/course/course-v1:OpenedX+DemoX+DemoCourse/home, maybe because of the videos?

**Comment by sarina** [comment] 2024-06-03 17:46
I guess you need _all_ of the units to not contain video in a given subsection for the time estimate to be displayed. This is a poor feature.

**Comment by mariajgrimaldi** [comment] 2024-06-06 02:47
Thank you, @sarina, for all the insight! Since this works with the correct setup, I'll close the issue.

**Closed by mariajgrimaldi** 2024-06-06 02:47 UTC
Labels: release testing, redwood
