### ISSUE TITLE
Internationalization is failing for certain languages and certain pages

### ISSUE THREAD

**Issue by jswope00** [openedx/wg-build-test-release#267] opened 2023-04-22 14:35 UTC
There appears to be great coverage for the English and Spanish languages on https://palm.demo.overhang.io/

But spot-checking other languages like German and Italian I am seeing gaps where pages are not translated. For what seems like most languages outside of English and Spanish, these pages are not being translated: 
1. Profile: https://prnt.sc/z4dGtXn-O0By
2. Account: https://prnt.sc/9s6A4RgMqbTR
3. Popups: https://prnt.sc/ICaT5O0Q8weT
4. Selective elements on Course homepage: https://prnt.sc/ICaT5O0Q8weT
5. Progress Page: https://prnt.sc/Sf9VH5YEDZY3
6. Dates: https://prnt.sc/MYIhC-JnYkHi

Happy to find more pages and languages if it is helpful, but this looks widespread and related to the MFEs to me.

**Comment by ghassanmas** [comment] 2023-05-03 08:02
As a translator of Arabic I have checked all the above mentioend repos and found the translation exists in source files, for ref
- [Learning/Progess page (and mainly all points other points)](https://github.com/openedx/frontend-app-learning/blob/open-release/olive.master/src/i18n/messages/ar.json) 
- [Account](https://github.com/openedx/frontend-app-account/blob/open-release/palm.master/src/i18n/messages/ar.json) 
- [Profile](https://github.com/openedx/frontend-app-profile/blob/open-release/olive.master/src/i18n/messages/ar.json)

**Comment by ghassanmas** [comment] 2023-05-03 09:28
Now for other langauges we would need to check the problem: 

1. If it's not translated then we would ask translator to review/translate the strings 
   1. Then we would need to wait for Jenkis jobs to sync translation on `**master**` which run usually every Mondy 
   1. Lastly someone would need to backport the commit from last step to `open-release/maser.palm` 
1. If it's a technical issue we would need to see why the translation aren't being pulled: 
   1. This has been a straight forward thing to resolve in the past, as I don't know who to reach out for, and it would also vary by the cause 

@brian-smith-tcril in the following PR you have asked for context 
  - openedx/frontend-app-course-authoring/pull/454 This PR is exactly what I refer to in step **`1.ii`** above

**Comment by sambapete** [comment] 2023-05-03 15:20
I don't seem to have any issues selecting fr_CA in the account MFE and having pages translated to fr_CA. It could be very language specific. Maybe some of the languages were the problems are occurring are not a 100% translated?

**Comment by DeanJayMathew** [comment] 2023-05-17 05:32
@ghassanmas @sambapete 

Which languages should we cover in testing? 

English
Spanish
Arabic
French

Any others you think should be part of the test plan?

**Comment by jyliugithub** [comment] 2023-05-24 17:42
Just checked Mandarin( Chinese) , a lot has not been synced ( especially Course, Progress, Date,Discussion) . Not sure if it is because of the cut off date ( Apr) or anything else.

**Comment by ghassanmas** [comment] 2023-05-24 18:14
@jyliugithub Thank you for testing. 
Checking the `frontend-app-learning` resource in Mandarin https://app.transifex.com/open-edx/edx-platform/language/zh_CN/, it's about 23% reviewed while 100% translated And you can only see from here it's only pulling hte reviewed strings https://github.com/openedx/frontend-app-learning/blob/master/src/i18n/messages/zh_CN.json .

**Comment by jyliugithub** [comment] 2023-05-24 20:54
@ghassanmas  I see. Thanks for letting me know. I will try to finish the reviewing of the frontend learning strings then test again. Give me a couple of days, I will update again here.

**Comment by pdpinch** [comment] 2023-06-14 01:23
Should the release notes include this as a "known issue"? If so please propose some text on the release notes PR at https://github.com/openedx/docs.openedx.org/pull/321

**Comment by mariajgrimaldi** [comment] 2023-07-10 14:02
Hi there! Do we have an update on this issue? I also noticed there is no clear solution -- eg. translate MFEs to german or fix chinese translations. Should we add one? So we know when this is done.

**Comment by jyliugithub** [comment] 2023-07-10 22:45
@mariajgrimaldi https://palm.demo.overhang.io/dashboard can not be accessed at the moment. Although the Chinese translation for frontend-app-learning is done, I can not check if the translation has been synced or not.

**Comment by mariajgrimaldi** [comment] 2023-08-07 13:25
@jyliugithub you can use this instance for tests: https://demo.openedx.overhang.io/ it's deployed using the latest Open edX release! Let us know how your testing goes.

**Comment by heldersepu** [comment] 2023-10-12 01:15
FYI @jswope00 ...
For the German and Italian langs, it a lot of translation is missing:
- https://github.com/openedx/frontend-app-account/blob/open-release/palm.master/src/i18n/messages/de.json
- https://github.com/openedx/frontend-app-account/blob/open-release/palm.master/src/i18n/messages/it.json

**Comment by heldersepu** [comment] 2023-10-12 03:13
Could it be that the selector has the wrong option?



![Image](https://github.com/openedx/wg-build-test-release/assets/545474/feafb1d5-f7a9-475a-ac55-fe33126a4f8b)

**Comment by heldersepu** [comment] 2023-10-12 03:18
It looks that the selector option is indeed the problem, I change the italian option to `it-IT` and save and it shows correctly
 
![Screenshot from 2023-10-11 23-15-34](https://github.com/openedx/wg-build-test-release/assets/545474/cd32729d-ae06-4490-834f-4a99bf58aeda)

**Comment by heldersepu** [comment] 2023-11-01 13:43
PR was merged, this issue can be closed

**Closed** 2024-04-29 17:14 UTC
Labels: palm testing
