### ISSUE TITLE
[Test failure] <TC_LEARNER_REDWOOD_8>: <Only one in-course experience sidebar can be open at a time failing>

### ISSUE THREAD

**Issue by lkatsikaris** [openedx/wg-build-test-release#404] opened 2024-11-06 12:58 UTC
### Release

Sumac

### Expected behavior

Only one sidebar can be opened at a time. When I expand a second sidebar while the opposite sidebar is open, the second sidebar expands while the other collapses.

### Actual behavior

When I expand a second sidebar while the opposite sidebar is open, the second sidebar still open. 

### Steps to reproduce

Given I am a user enrolled in a course on an in-course experience page on an instance with the _courseware.enable_navigation_sidebar_ is enabled. When I expand a second sidebar while the opposite sidebar is open, the second sidebar still open.

[Screencast from 11-06-2024 09:53:45 AM.webm](https://github.com/user-attachments/assets/c308e50a-b429-41c1-beba-24efa43b4c21)

**Comment by jciasenza** [comment] 2024-11-15 20:06
I made a PR #1509

**Comment by mariajgrimaldi** [comment] 2024-12-02 09:54
@jciasenza: I see your PR was already merged to master. That's great news! Could you give us a hand opening a PR against open-release/sumac? master so we can include this fix in the sumac release? We'd appreciate it!

**Comment by crathbun428** [comment] 2024-12-02 19:33
@mariajgrimaldi, @jciasenza, @lkatsikaris - Maybe I'm reading this wrong, but the video does not show 2 sidebars being open at the same time. This test intends to make sure you can't open a LEFT and RIGHT sidebar at the same time. 

The left sidebar can and should be able to expand or collapse multiple sections/subsections at the same time. If that is what this bug is reporting, this is not a bug. Please confirm.

**Comment by mariajgrimaldi** [comment] 2024-12-02 19:39
@crathbun428: I do think that what this is reporting, and this new behavior was included in the sidebar. Should we contact the maintainers to revert it?

**Comment by mariajgrimaldi** [comment] 2024-12-02 20:00
@crathbun428: can you comment in [this PR](https://github.com/openedx/frontend-app-learning/pull/1519) tagging Farhaan explaining the situation?

**Comment by crathbun428** [comment] 2024-12-02 20:14
@mariajgrimaldi - done

**Comment by angonz** [comment] 2024-12-04 14:38
I'll close this issue as the PR does not reflect the test case.

**Closed by angonz** 2024-12-04 14:38 UTC
Labels: bug, release testing, sumac

**Comment by farhaanbukhsh** [comment] 2024-12-04 15:56
why are we closing this issue?

**Comment by angonz** [comment] 2024-12-04 16:00
Because the test case is that a right sidebar (notifications, forum) and a left sidebar (navigation) cannot be open at the same time. If you open the right sidebar, the left sidebar should hide, and vice-versa. 
The PR mistakenly understood that two sections in the navigation sidebar should not be unfolded at the same time.

**Comment by farhaanbukhsh** [comment] 2024-12-04 16:32
@angonz Understood, should we open an issue to add this test case?

**Comment by mariajgrimaldi** [comment] 2024-12-04 16:35
Thank you all, @farhaanbukhsh, @angonz, and @lkatsikaris! This was mainly my mistake because I needed to read into this further. Farhaan already opened the PR to revert the changes in master, and since no backport was opened sumac wasn't affected. 

Andrés, can we clarify the test case as you did in [this](https://github.com/openedx/wg-build-test-release/issues/404#issuecomment-2517869328) comment?
