### ISSUE TITLE
[ECOM > Create a course seat] > After creating course I am not able to open its detail page 

### ISSUE THREAD

**Issue by fayyazahmed66** [openedx/wg-build-test-release#301] opened 2023-08-11 06:13 UTC
I was testing the course seat creation on Ecom and I noticed that when I create a course on Studio having `course run` like 2000.01, and then create a course seat on Ecom. It will create course seats successfully. But when I try to open that course seat to see the details, it doesn't show anything. 
The problem is with the `course run` has zero after `.` operator. i-e 2000.01. We need to fix the regex I think. 
**Steps to reproduce:**

1. Create a course on studio and set its course run to like 2000.01
2. Publish the course
3. Go to Ecom and create a course seat
4. check the course seat detail page after creating a seat

**Expected result:**
It should show course seat detail.

**Actual Result:**
`Not found` is showing in the network tab. 

**Note: I can reproduce this issue if we installed the `ECOM` service on our `Demo` instance.** 

<img width="1678" alt="Screenshot at Aug 08 15-07-35" src="https://github.com/openedx/wg-build-test-release/assets/55684124/04538ce8-3b6c-4b86-a370-e9316d412d93">

<img width="1679" alt="Screenshot at Aug 08 15-20-11" src="https://github.com/openedx/wg-build-test-release/assets/55684124/b27dc9a8-4b3d-4bf4-9fe3-baac90f9dcd0">

**Comment by mariajgrimaldi** [comment] 2023-09-05 14:13
I don't have access to an e-commerce installation, so I can't test this to confirm the issue. @sambapete can you lend us a hand here? Thanks!

Also, if you think you know how to solve this @fayyazahmed66, open a PR! We would appreciate it. Not a lot of us have access to e-commerce installations.

**Comment by sambapete** [comment] 2023-09-05 14:28
Thanks for the reminder @mariajgrimaldi. I had planned to look into it when @fayyazahmed66 raised the issue and try it on one of our systems but completely forgot about it after a few days.

Right now, I can test it on a nutmeg.3 instance (a copy of our production instance) and a palm.2 instance (where we are testing our own fork).

I will first try to reproduce the problem.

**Comment by sambapete** [comment] 2023-09-05 14:34
@fayyazahmed66 I would need more details about what you were trying.

Here are some screenshots from a course I just created under palm.2

**Comment by sambapete** [comment] 2023-09-05 14:44
I see what you mean now. It is when trying to access the course in the course administration tool not in the products page for Oscar.

<img width="1810" alt="Capture d’écran, le 2023-09-05 à 10 44 03" src="https://github.com/openedx/wg-build-test-release/assets/8906669/88511a43-6dfb-4d51-9148-83304ffaa86d">

**Comment by sambapete** [comment] 2023-09-05 14:57
I also tried a course with a session ending with .9 instead of .09 and I had the same behavior.

course-v1:UMontreal+Session101.2+2023.9 and course-v1:UMontreal+Session101+2023.09

**Comment by sambapete** [comment] 2023-09-05 15:33
I don't know how to solve it yet, but it is clear the problem would be in the ecommerce/ecommerce/core/constants.py file where COURSE_ID_REGEX is defined.

it is currently

**Comment by sambapete** [comment] 2023-09-05 19:59
Based on the substrings I suspect that it should be **COURSE_ID_REGEX = r'[^/+]+(/|+)[^/+]+(/|+)[^/+]'** but I will try it first in my fork of ecommerce.

**Comment by sambapete** [comment] 2023-09-05 20:16
This does result in a new problem when I access /courses in ecommerce

<img width="398" alt="Capture d’écran, le 2023-09-05 à 16 05 41" src="https://github.com/openedx/wg-build-test-release/assets/8906669/17df20ea-5404-4e8d-b402-0d581334a70b">

It could potentially be a problem with the table not with the regex.

**Comment by sambapete** [comment] 2023-09-06 18:35
After trying a few things, I discovered that the issue seems limited to courses where the sessions ends with a . (dot) followed with a number. I tried ending the session with a . (dot) by itself or followed by a letter and it worked.

One thing I noticed is that when a seat is opened in order to edit it it calls

**Comment by sambapete** [comment] 2023-09-06 23:17
I don't understand why it behaves differently when the course id ends with a . (dot) followed by a number. See the screenshots:

<img width="1685" alt="Capture d’écran, le 2023-09-06 à 19 14 27" src="https://github.com/openedx/wg-build-test-release/assets/8906669/a052436f-ae03-4af7-81c7-43a888fb37b7">

<img width="1688" alt="Capture d’écran, le 2023-09-06 à 19 14 40" src="https://github.com/openedx/wg-build-test-release/assets/8906669/7c55b7ba-f78e-43e5-95ed-ea0c8d688d86">

**Comment by regisb** [comment] 2023-09-19 07:42
Reproducing the issue is easy with Tutor:

1. Enable discovery and ecommerce plugins, run `tutor local launch`
2. Create admin user in ecommerce: `tutor local run ecommerce ./manage.py shell -c "from django.contrib.auth import get_user_model; get_user_model().objects.filter(email='YOUREMAIL@ACME.COM').update(is_staff=True, is_superuser=True)"`
3. In studio, create course with ID course-v1:overhangio+alpha+2023.09
4. In http://ecommerce.local.overhang.io/courses/ create course with the same ID
5. Open http://ecommerce.local.overhang.io/courses/course-v1:overhangio+alpha+2023.09/

**Comment by regisb** [comment] 2023-09-19 10:57
The problem does _not_ come from the COURSE_ID_REGEX. It comes from the Django REST framework.

To troubleshoot I opened a shell in the ecommerce container:

    tutor dev run ecommerce ./manage.py shell

Import Django url resolver:

    from django.urls import resolve

Then, compare:

```
>>> resolve("/api/v2/courses/course-v1:overhangio+alpha+2023/")
ResolverMatch(func=ecommerce.extensions.api.v2.views.courses.CourseViewSet, args=(), kwargs={'pk': 'course-v1:overhangio+alpha+2023'}, url_name=course-detail, app_names=['api', 'v2'], namespaces=['api', 'v2'], route=^api/v2/courses/(?P<pk>[^/+]+(/|\+)[^/+]+(/|\+)[^/]+)/$)
```

with:

```
>>> resolve("/api/v2/courses/course-v1:overhangio+alpha+2023.09")
ResolverMatch(func=ecommerce.extensions.api.v2.views.courses.CourseViewSet, args=(), kwargs={'pk': 'course-v1+overhangio+alpha+2023', 'format': '09'}, url_name=course-detail, app_names=['api', 'v2'], namespaces=['api', 'v2'], route=^api/v2/courses/(?P<pk>[^/+]+(/|\+)[^/+]+(/|\+)[^/]+)\.(?P<format>[a-z0-9]+)/?$)
```

Notice the `'format': '09'` part. "09" is interpreted as a [format suffix](https://www.django-rest-framework.org/api-guide/format-suffixes/#format-suffixes). Because "09" is an unknown format calling the url results in 404. 

The problem can be diagnosed more precisely with:

```
>>> import ecommerce.extensions.api.v2.views.courses as course_views
>>> from rest_framework_extensions.routers import ExtendedSimpleRouter as SimpleRouter
>>> from rest_framework.urlpatterns import format_suffix_patterns
>>> router = SimpleRouter()
>>> router.register(r'courses', course_views.CourseViewSet, basename='course')
>>> format_suffix_patterns(router.urls)
[<URLPattern '^courses/$' [name='course-list']>, <URLPattern '^courses\.(?P<format>[a-z0-9]+)/?$' [name='course-list']>, <URLPattern '^courses/(?P<pk>[^/+]+(/|\+)[^/+]+(/|\+)[^/]+)/$' [name='course-detail']>, <URLPattern '^courses/(?P<pk>[^/+]+(/|\+)[^/+]+(/|\+)[^/]+)\.(?P<format>[a-z0-9]+)/?$' [name='course-detail']>, <URLPattern '^courses/(?P<pk>[^/+]+(/|\+)[^/+]+(/|\+)[^/]+)/publish/$' [name='course-publish']>, <URLPattern '^courses/(?P<pk>[^/+]+(/|\+)[^/+]+(/|\+)[^/]+)/publish\.(?P<format>[a-z0-9]+)/?$' [name='course-publish']>]
```

Notice the course-detail url pattern:

```
<URLPattern '^courses/(?P<pk>[^/+]+(/|\+)[^/+]+(/|\+)[^/]+)\.(?P<format>[a-z0-9]+)/?$' [name='course-detail']>
```

The "format" part from the regex matches ".09":

```
>>> re.match(r'^courses/(?P<pk>[^/+]+(/|\+)[^/+]+(/|\+)[^/]+)\.(?P<format>[a-z0-9]+)/?$', 'courses/course-v1+overhangio+alpha+2023.09').groupdict()
{'pk': 'course-v1+overhangio+alpha+2023', 'format': '09'}
```

This "non-formatted" detail url does not match because the url does not include a trailing slash:  `<URLPattern '^courses/(?P<pk>[^/+]+(/|\+)[^/+]+(/|\+)[^/]+)/$' [name='course-detail']>`. Notice how the trailing slash is optional in the "formatted" url.

This seems to be a related issue: https://stackoverflow.com/questions/27963899/django-rest-framework-using-dot-in-url

We can resolve this issue by appending a trailing slash to the url. This url is created by backbone in "course_model.js". I managed to fix the issue with the following piece of code:

```

urlRoot: '/api/v2/courses/',
url: function() {
    return Backbone.Model.prototype.url.call(this) + '/';
},
```

When we define the above "url" method, the course page loads fine.

If this is a satisfactory fix then I can open a PR.

**Comment by sambapete** [comment] 2023-09-19 15:16
Thanks for the detailed explanation @regisb 
I learned a few things reading it.

I agree that adding a trailing slash to the url does seem to solve the current issue and it's what I had noticed during my testing when I added a trailing slash to the url in order to see the JSON data.

I would be fine with this PR. Thanks again for your help.

**Comment by mariajgrimaldi** [comment] 2024-10-29 11:18
I left a comment on the PR, but if we don't get the PR merged, I'll be closing this soon, considering that e-commerce will be archived after sumac.

**Comment by mariajgrimaldi** [comment] 2024-11-22 18:20
Ecommerce was archived a few weeks ago: https://github.com/openedx-unsupported/ecommerce/pull/4033

So I'm closing this issue now.

**Closed by mariajgrimaldi** 2024-11-22 18:20 UTC
Labels: release testing, quince
