### ISSUE TITLE
[Test failure] <TC_AUTHOR_REDWOOD_7>: < un-enrollment is not reflecting>

### ISSUE THREAD

**Issue by fayyazahmed66** [openedx/wg-build-test-release#368] opened 2024-05-28 09:51 UTC
### Release

Redwood

### Expected behavior

un-enrollment should also reflected in this stat. 

### Actual behavior

un-enrollment isn't reflected in this stat. 

### Steps to reproduce

1. Go to instructor tab > Reports
2. Click on the course dashboard stat
3. unenroll from this course with a learner user
4. check stat again in current enrolees

<img width="1440" alt="Screenshot 2024-05-28 at 2 43 40 PM" src="https://github.com/openedx/wg-build-test-release/assets/55684124/3afd14b1-4a72-4f22-8c70-784e252c4d1f">

### Additional information

https://redwood.demo.edly.io/courses/course-v1:OpenedX+DemoX+DemoCourse/instructor#view-aspects

**Comment by fayyazahmed66** [comment] 2024-05-28 09:52
label: redwood release testing

**Comment by Ian2012** [comment] 2024-05-30 15:21
Thanks for the report, the issue is that the query counts `enrollment_events` instead of only counting the latest enrollment event per learner.

**Comment by crathbun428** [comment] 2024-06-03 19:29
Not a release blocker, but should be fixed since current enrollees should show the number of currently enrolled learners, not total enrollees (all learners who have enrolled in the course).

**Comment by bmtcril** [comment] 2024-06-04 19:32
If this isn't fixed in Daniela's next round of changes we'll fix it as a fast follow, it should be a quick fix I just don't want it to get lost integrating the next set of dashboard changes.

**Comment by mariajgrimaldi** [comment] 2024-09-16 11:34
Hi there, @Ian2012 @bmtcril. Could you let me know if this was ever fixed? Thanks.

**Comment by bmtcril** [comment] 2024-09-16 13:11
Yes, I believe that was fixed here: https://github.com/openedx/tutor-contrib-aspects/pull/862/

**Closed by bmtcril** 2024-09-16 13:11 UTC
Labels: release testing, redwood
