### ISSUE TITLE
[Test failure] TC_LEARNER_11: CORS error when unliking SSO account in account settings

### ISSUE THREAD

**Issue by GlugovGrGlib** [openedx/wg-build-test-release#376] opened 2024-05-31 15:48 UTC
### Release

Redwood

### Expected behavior

- SSO account is successfully unliked
<img width="1002" alt="image" src="https://github.com/openedx/wg-build-test-release/assets/22370912/4c41a2ab-7881-44cc-b624-c9aadc9249fd">

### Actual behavior

- Error is displayed:
<img width="1705" alt="Screenshot 2024-05-31 at 18 31 04" src="https://github.com/openedx/wg-build-test-release/assets/22370912/f5792303-6433-4231-877f-2f3d915468d8">

- After page reload the SSO account is unlinked 

### Steps to reproduce

1. [Configure TPA auth for Open edX](https://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/configuration/tpa/tpa_integrate_open/tpa_oauth.html)
2. Login or Register via third-party authentication
3. Go to account settings > Linked Accounts section
4. Click Unlink {TPA_Name} account
5. Observe error in interface and browser console 

### Additional information

Request to `/auth/disconnect/{backend-slug}/{user_social_auth_id}/`  is made when unlinking SSO, and 302 code redirect to location `/dashboard` is returned.
<img width="1798" alt="Screenshot 2024-05-31 at 18 32 04" src="https://github.com/openedx/wg-build-test-release/assets/22370912/92e51b01-1744-4406-a0be-7b8879f60c55">

- The similar problem happens when changing the language on the account settings page: https://github.com/openedx/wg-build-test-release/issues/347

**Comment by mariajgrimaldi** [comment] 2024-06-02 15:47
I mentioned the CORS error in the issue 1052 linked above. I'll let you know once I know more.

**Comment by mariajgrimaldi** [comment] 2024-06-02 23:33
Thank you so much for the report! The SSO account is unlinked, but an error is raised, just like with the language issue.

**Comment by mariajgrimaldi** [comment] 2024-10-07 11:07
The language issue had a different root cause than a CORS issue (see [here](https://github.com/openedx/frontend-app-account/issues/1052#issuecomment-2368317629) for more details), so as I mentioned above, these two issues might not be related.

**Comment by mariajgrimaldi** [comment] 2024-10-22 21:03
Fixed by https://github.com/openedx/frontend-app-account/pull/1139!

**Closed by mariajgrimaldi** 2024-10-22 21:03 UTC
Labels: release testing, redwood
