### ISSUE TITLE
From the Profile page, the Account link in the dropdown does not work

### ISSUE THREAD

**Issue by jswope00** [openedx/wg-build-test-release#266] opened 2023-04-22 13:58 UTC
When I am on the profile page, the 'Account' button in the top right drop-down does not appear to work. 
Looking at console, it seems there is no target for the link: 
https://prnt.sc/MOJnwe5hFa_A

**Comment by ghassanmas** [comment] 2023-04-25 12:53
This is duplicate of #268

**Closed** 2023-05-02 14:39 UTC
